# Generated by Django 4.1.2 on 2022-11-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_scope_alter_scope_article_alter_scope_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scope',
        ),
    ]
