# Generated by Django 4.1.2 on 2022-11-08 20:28

import articles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='tags_scope', through='articles.Scope', to='articles.tag'),
        ),
        migrations.AddField(
            model_name='scope',
            name='main_tag',
            field=models.BooleanField(default=False, verbose_name=articles.models.Tag),
        ),
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_1', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_1', to='articles.tag'),
        ),
    ]
