# Generated by Django 4.1.2 on 2022-11-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_scope_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='is_main',
            new_name='Главная рубрика',
        ),
    ]
