# Generated by Django 4.1.2 on 2022-11-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_is_main_scope_главная рубрика'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='Главная рубрика',
            new_name='is_main',
        ),
    ]
