# Generated by Django 4.1.2 on 2022-11-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_rename_главная рубрика_scope_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
