# Generated by Django 4.1.2 on 2022-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_studentteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='rel_stud_teachers', to='school.teacher'),
        ),
    ]
